# values.yml에 있는 services들을 순회하면서 각 서비스에 대한 Service 리소스를 일괄 생성.

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
