server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  # ??? ???? ??
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/stephen/Desktop/develop/git-local-repo
        git:
          # 호스트 키는 SSH 프로토콜을 통해 Git 저장소에 접근할 때 Git 서버의 신뢰성을 검증하기 위한
          # 호스트 키를 제공해야 합니다.
          uri: git@github.com:LeeKM321/cloud-config-settings.git
          default-label: main
          host-key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          host-key-algorithm: "ecdsa-sha2-nistp256"
          private-key: |
            ${GIT_PRIVATE_KEY}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
logging:
  level:
    org.springframework.cloud.config: debug
