server:
  port: 8888

spring:
  application:
    name: config-service
  # ??? ???? ??
  cloud:
    config:
      server:
        git:
          uri: file:///Users/stephen/Desktop/develop/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
