server:
  port: 8888

spring:
  application:
    name: config-service
  # ??? ???? ??
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeeKM321/cloud-config-settings.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
